### ISSUE TITLE
Where to set Papaparse Config

### ISSUE THREAD

**Issue by kellykampen** [beamworks/react-csv-importer#22]
Hi, this is exactly what I have been looking for. 

I can't seem to find where I can set the Papaparse configuration.  I need to modify the delimiter and a few other items that I use with Papaparse. 

Thanks in advance.

**Comment by unframework** [comment]
Hey, thanks for the kind words! Papaparse config is a good feature to add, I am planning to do it in the next day or two.

**Comment by kellykampen** [comment]
@unframework 
Fantastic, looking forward to it.  I will hold off until then to add this part to my project.

**Comment by unframework** [comment]
Just published version 0.3.0 with the relevant changes - the module README has more info (basically, several PapaParse config options are passable as props now).

Hope this helps! Closing for now, please re-open if any issues come up.

**Comment by kellykampen** [comment]
You're a legend. Thanks so much.
