### ISSUE TITLE
[Feature Request] Auto Map Column Headers

### ISSUE THREAD

**Issue by mmmaxi** [beamworks/react-csv-importer#29]
It would be awesome to pass in an input parameter which automatically tries to map column headers to the Importfields based on the string in the import field and column header.

This would increase usability for import files a large amount of columns.

**Comment by unframework** [comment]
Thanks for the suggestion! Yep this is actually next on my list of ease-of-use improvements. In fact, human-readable label of import field could probably be already used for auto-match (with opt-out just in case). And could even supply a set of hints to try for auto-matching... Coming soon!

**Comment by unframework** [comment]
Hey, just added this feature in v0.4.0. As I type this, I realize that I should add an opt-out flag for this, but meanwhile I hope this helps!
