### ISSUE TITLE
[Feature Request] Handle New Fields

### ISSUE THREAD

**Issue by jessehanley** [beamworks/react-csv-importer#36]
Hey @unframework, 

Thanks so much for creating this library. We're having a blast with it! We were using an Ent. solution until they hit us with a scary sales call so had to make the switch — couldn't stomach it as a wee little bootstrapper 🥺

Quick question: what's the easiest way to dynamically add fields based on the CSV uploaded? 

Say, in our product, someone uploads a spreadsheet with 20 unique columns some of which we've never seen before (+ some which we have). We'd like users to basically be like "yes, match all these but also add these". I think what I want is an `onUpload` where I can call the columns, set them, then just iterate over each to add all the fields on the matching screen.

Thoughts?

**Comment by unframework** [comment]
Hi Jesse, happy that this could be useful for you!

So if I understand correctly, you want to let users upload custom fields? With some kind of e.g. dynamic pattern match filter, I presume...

If the field list changes just based on the known CSV header set (+ base known set) I wonder if a render-prop would solve this issue nicely. I.e. the invocation would look like this:

```js
<Importer>
  {({ file, preview } = {}) => <>
    <ImporterField name="coreFieldA" />
    <ImporterField name="coreFieldB" />

    {preview && preview.columns
      .filter(col => col.name.startsWith('myCustomField_'))
      .map(col =>
        <ImporterField name={col.name} label={`Your custom field: ${col.name}`} />
      )
    }
  </>}
</Importer>
```

Thoughts? Thanks for suggesting this by the way.

**Comment by jessehanley** [comment]
That would 100% solve my issue and be super helpful!!!

**Comment by unframework** [comment]
Ok, I will try to push this fix within the next day or two, thanks again for the input!

**Comment by jessehanley** [comment]
Oh wow! Amazing!!!

**Comment by unframework** [comment]
Please try v0.5.0, should have the necessary fields now (see README for a brief description). Cheers!

**Comment by jessehanley** [comment]
✨ Implemented ✨

Thank you!!! 

![image](https://user-images.githubusercontent.com/6285267/113557961-cf4a7e00-9639-11eb-9892-2dab717f0260.png)
