### ISSUE TITLE
File Preview text color

### ISSUE THREAD

**Issue by krewllobster** [beamworks/react-csv-importer#41]
For some reason it seems that $invertedTextColor doesn't get applied to the preview text under "Raw File Contents". I have black or dark text on top of the #404040 $invertedBgColor.

<img width="349" alt="Screen Shot 2021-05-07 at 10 07 08 AM" src="https://user-images.githubusercontent.com/9201597/117462972-2be0d780-af1d-11eb-8a8d-e8a380d5047e.png">

**Comment by GodAlmighty990** [comment]
were you ever able to fix this? Also How can I make changes to the css, do I need to make a custom fork of the project?

**Comment by unframework** [comment]
Hey @GodAlmighty990, I was never able to reproduce the issue, unfortunately. If you are experiencing the same visual bug, let me know which browser this is happening in!

Re: making changes to CSS, you do not need to create a custom fork. It might be easiest to layer on your own CSS styles in addition to stock CSS - take a look at the selectors that are used in the SCSS files in source code, you can use them in your own stylesheet (with e.g. an extra class selector to "win out" over the stock ones). Hope this helps!

**Comment by GodAlmighty990** [comment]
This helps! Thank you!

Keith Peiker
(720) 979-2696
Brothers Restoration
www.BrothersRestoCo.com
10621 Irma Dr Unit G, Northglenn CO 80233
________________________________

**Comment by unframework** [comment]
Closing for now, happy to investigate when more info comes in.
