### ISSUE TITLE
Great stuff, how about CSS styling

### ISSUE THREAD

**Issue by vongohren** [beamworks/react-csv-importer#48]
I just wonder, the self contained styling, is it not overrridable?
If we were to add more information it has to come around the selfcontained box?

Or do you have any thoughts on how to do this

**Comment by GodAlmighty990** [comment]
agreed.. did you find a way to do this? the css is not great to say the least....

**Comment by vongohren** [comment]
@GodAlmighty990 no we ended up making our own handler for this

**Comment by unframework** [comment]
Hey everyone, the built-in CSS is intentionally basic and one should be able to override it by adding stylesheets that reference the same CSS classes. Inherited font family and font size do affect the styling in the widget, though, as well.

I am planning a more extensive customization approach, to allow changing individual UI elements too, but it has been a busy end of 2021 for me unfortunately. Either way, thanks for checking out this library! Will close the issue for now.
