### ISSUE TITLE
Allow to customise SOURCES_PAGE_SIZE

### ISSUE THREAD

**Issue by sara-jegorova** [beamworks/react-csv-importer#72]
Currently fields step is not very mobile-friendly, mostly because 5 items is too much for a small screen:
![Screenshot 2022-03-22 at 14 31 04](https://user-images.githubusercontent.com/86767207/159482546-f276220b-9f05-4fe0-9a2d-d2b958aa018f.png)

It would be great to be able to customise SOURCES_PAGE_SIZE from https://github.com/beamworks/react-csv-importer/blob/master/src/components/fields-step/ColumnDragSourceArea.tsx#L13 , or better yet, change it based on screen width.

**Comment by unframework** [comment]
Released a quick fix in v0.8.0: there is now a setting called `displayColumnPageSize` that controls the above. It is set to 5 by default, smaller values might look better on mobile screens.

Similarly, a new setting called `displayFieldRowSize` controls the drag-drop destination field row display; the default is 4. I added a storybook example for these.

I still plan to come up with a proper mobile-friendly UI for v1, but for now this will do hopefully. Thanks again for the suggestion!
