### ISSUE TITLE
OnComplete Showing Upload More instead of Finish

### ISSUE THREAD

**Issue by dymyll** [beamworks/react-csv-importer#80]
Hello, 
I am trying to use the Importer library and all is well, however, I noticed when using the 
_onComplete_ and _onClose_ while setting the _restartable_  attribute to true. The button for onClose will show "Upload More" instead of "Finish".
I am sure this is a minor bug, but I cannot locate where to fix the issue? 

Expecting to see: 
**Upload More** and **Finish**

`<Importer
          assumeNoHeaders={false} 
          restartable={true} 
          onStart={({ file, preview, fields, columnFields }) => {
              setFile(file);
          }}
          processChunk={async (rows, { startIndex }) => {
            for (let row of rows) {
                console.log("Row: ", row)
            }
          }}
          onComplete={({ file, preview, fields, columnFields }) => {
            if (file) {
                 // Do something with file
              }
          }}
          onClose={({ file, preview, fields, columnFields }) => {
            //goToMyAppNextPage();
          }}
           escapeChar={true}
           skipEmptyLines={true}
        >
          <ImporterField name="name" label="Name" />
          <ImporterField name="columna" label="COLUMN A" optional />
          <ImporterField name="columnb" label="COLUMN B" optional />
        </Importer>`

![Screen Shot 2022-07-08 at 11 26 41 AM](https://user-images.githubusercontent.com/31488060/178032575-afba29e9-9a84-4c04-bc24-0cb1020ed9cb.png)

**Comment by unframework** [comment]
Hi Dymyll, thanks for reporting this - I just checked and was able to reproduce the issue. Will merge a fix very shortly, might be a bit longer to publish a new version though.

**Comment by unframework** [comment]
Released the fix in v0.8.0.
