### ISSUE TITLE
<button> elements have type="button" missing, causing autosubmitting forms

### ISSUE THREAD

**Issue by dorukgezici** [beamworks/react-csv-importer#93]
Hey, thanks for the library!

I have just run into an edge case. My `<Importer>` is inside a `<form>`, so since the default type for buttons is "submit" and there is no type defined for the button [IconButton](https://github.com/beamworks/react-csv-importer/blob/58995b04e3c70f90670f1846453f4ab0e43d27ff/src/components/IconButton.tsx), it tries to submit my form whenever I change the page while mapping fields.

I can work on a PR to define `type="button"` to stop auto-submitting forms if you would like. I currently am catching the faulty submits in my `onSubmit `function using a flag.

**Comment by unframework** [comment]
Oh that's a mistake on my part for sure! Thanks for reporting it, I should be able to make a PR by Monday ish.

**Comment by dorukgezici** [comment]
Np, thanks for the fix!

**Comment by unframework** [comment]
Released in v0.8.0.
